const express = require("express")
const app = express()
const connectdb = require("./connection/db")
const router = require("./routes/router")
app.use(express.json())
app.use("/",router)
app.listen(4000,console.log("server connected"))