
export const environment = {
  production: false,
  
  posturl:'register',
  loginurl:"login",
  getalluser:'getalluser',
  logoutuser:'logout',
  myaccount:'getuser',
  updateuser:'updateuser',
  changepassword:'changepassword',
  deleteuser:"deleteuser",
  searchuser:'search',
  updatecourse:'updatecourse',
  addcourse:"addcourse",
  deletecourse:"deletecourse",
  profile:'public',
  deleteprofile:'public',
  inlineadduser:"adduser",
  inlineupdatesuer:'updateinlineuser',
  inlinedeleteuser:'deleteinlineuser',
  inlinefinduser:'findinlineusers',
  findteam:'findteam',
  addteam:'addteam',
  addchild:'addchild',
  updateteam:'updateteam',
  updatechild:'updatechild',
  deleteteam:'deleteteam',
  deletechild:'deletechild',
  arrayremoveitem:'arrayremoveitem',
  changearray:'changearray',
  findteambyid:'findteambyid',
  zip:'zipfile'
};
