const router = require("express").Router()
const Controller = require('../Controller/Usercontroller')
router.post("/register",Controller.Register)
router.post("/login",Controller.Login)
router.get("/getuser/:id", Controller.verifytoken,Controller.getuserById)
router.get('/getalluser',Controller.getAllUser)
router.put('/updateuser/:id',Controller.verifytoken,Controller.updateUserById)
router.delete('/deleteuser/:id',Controller.verifytoken,Controller.Deleteuser)
router.get('/changepassword/:id',Controller.ChangePassword)
router.get('/logout',Controller.Logout)
module.exports = router